---
###############################################################################
#
# loop_sites.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# SETTING VARIABLES
###############################################################################

- name: "Checking if required variables are defined"
  ansible.builtin.assert:
    that:
      - nginx_sites is defined
    fail_msg: "All tests did not pass"

###############################################################################
# LOOPING THROUGH SITES TO BE ADDED
###############################################################################

- name: "Looping through sites"
  ansible.builtin.include_tasks: "{{ state }}.yml"
  loop: "{{ nginx_sites }}"
  loop_control:
    loop_var: nginx_site
