---
###############################################################################
#
# main.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# CHECKING REQUIREMENTS
###############################################################################

- name: "Checking if operating system is supported"
  ansible.builtin.fail:
    msg: "Unsupported operating system: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }}"
  when: >
    iac_supported_os | selectattr('name', 'equalto', ansible_facts['distribution'])
                     | selectattr('versions', 'contains', ansible_facts['distribution_major_version'])
                     | list
                     | length == 0

- name: "Checking if service_key is found from variables"
  ansible.builtin.fail:
    msg: "iac_blueprint or iac_blueprint.nginx is not defined"
  when:
    - iac_blueprint is not defined
    - iac_blueprint.nginx is not defined

###############################################################################
# SETTING VARIABLES
###############################################################################

- name: "Setting what virtual hosts are to be configured"
  ansible.builtin.set_fact:
    nginx_sites: "{{ iac_blueprint.nginx.sites }}"

- name: "Checking proxy address if it's defined"
  ansible.builtin.set_fact:
    proxy_host: "{{ (http_proxy | regex_replace('^https?://', '')).split(':')[0] }}"
    proxy_port: "{{ (http_proxy | regex_replace('^https?://', '')).split(':')[1] | int }}"
  when: >
    (
      (http_proxy is defined and http_proxy != "")
      or (https_proxy is defined and https_proxy != "")
    )
    and (inventory_hostname not in (no_proxy | default("") | split(",")))

- name: "Checking that proxy connection is working if it's defined"
  ansible.builtin.wait_for:
    host: "{{ proxy_host }}"
    port: "{{ proxy_port }}"
    state: "started"
    timeout: 3
  when: >
    (
      (http_proxy is defined and http_proxy != "")
      or (https_proxy is defined and https_proxy != "")
    )
    and (inventory_hostname not in (no_proxy | default("") | split(",")))

###############################################################################
# CHECKING STATES
###############################################################################

- name: "STATE: Ensure Nginx installation and configuration is present"
  ansible.builtin.include_tasks: install.yml
  when: state == 'install'

- name: "STATE: Ensure Nginx installation and configuration is absent"
  ansible.builtin.include_tasks: uninstall.yml
  when: state == 'uninstall'

- name: "STATE: Ensure Nginx installation is present"
  ansible.builtin.include_tasks: present.yml
  when: state == 'present'

- name: "STATE: Ensure Nginx installation is absent"
  ansible.builtin.include_tasks: absent.yml
  when: state == 'absent'

- name: "STATE: Ensure Nginx sites are present"
  ansible.builtin.include_tasks: loop_sites.yml
  vars:
    nginx_state: "{{ state }}"
  when: state == 'site_present'

- name: "STATE: Ensure Nginx sites are absent"
  ansible.builtin.include_tasks: loop_sites.yml
  vars:
    nginx_state: "{{ state }}"
  when: state == 'site_absent'

- name: "STATE: Ensure Nginx site is enabled"
  ansible.builtin.include_tasks: loop_sites.yml
  vars:
    nginx_state: "{{ state }}"
  when: state == 'site_enabled'

- name: "STATE: Ensure Nginx site is disabled"
  ansible.builtin.include_tasks: loop_sites.yml
  vars:
    nginx_state: "{{ state }}"
  when: state == 'site_disabled'

- name: "STATE: Ensure Nginx is started"
  ansible.builtin.include_tasks: started.yml
  when: state == 'started'

- name: "STATE: Ensure Nginx is stopped"
  ansible.builtin.include_tasks: stopped.yml
  when: state == 'stopped'
