---
###############################################################################
#
# package_absent.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# SETTING VARIABLES
###############################################################################

- name: "Checking if required variables are defined"
  ansible.builtin.assert:
    that:
      - iac_package is defined
    fail_msg: "All tests did not pass"

###############################################################################
# ENSURING PACKAGE IS PRESENT
###############################################################################

- name: "Ensuring packages are installed"
  ansible.builtin.dnf:
    name: "{{ iac_package }}"
    sslverify: "{{ dnf_sslverify | default(omit) }}"
    validate_certs: "{{ dnf_validate_certs | default(omit) }}"
    disable_gpg_check: "{{ dnf_disable_gpg_check | default(omit) }}"
    state: "absent"
  environment:
    http_proxy: "{{ http_proxy | default(omit) }}"
    https_proxy: "{{ https_proxy | default(omit) }}"
    no_proxy: "{{ no_proxy | default(omit) }}"
  when: iac_package is defined

- name: "Writing log"
  ansible.builtin.include_tasks: log_write.yml
  vars:
    iac_log_write: "Ensured {{ iac_package }} was uninstalled"
  when: iac_package is defined
