---
###############################################################################
#
# server_disabled.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# SETTING VARIABLES
###############################################################################

- name: "Setting variables"
  ansible.builtin.set_fact:
    nginx_server_port: "{{ nginx_server.listen | regex_search('([0-9]{2,5})(?!\\.)\\b') }}"

- name: "Checking if required variables are defined"
  ansible.builtin.assert:
    that:
      - nginx_etc_directory is defined
      - nginx_server is defined
      - nginx_server_port is defined
      - nginx_site.name is defined
    fail_msg: "All tests did not pass"

###############################################################################
# ENSURING SERVER IS DISABLED
###############################################################################

- name: "Remove symbolic link for server"
  ansible.builtin.file:
    path: "{{ nginx_etc_directory }}/sites-enabled/{{ nginx_site.name }}_{{ nginx_server_port }}"
    state: absent

- name: "Writing log"
  ansible.builtin.include_tasks: log_write.yml
  vars:
    iac_log_write: "Ensured {{ nginx_site.name }} was disabled"
