---
###############################################################################
#
# server_present_with_configuration.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# SETTING VARIABLES
###############################################################################

- name: "Setting variables"
  ansible.builtin.set_fact:
    nginx_server_port: "{{ (nginx_server.listen | regex_search('([0-9]{2,5})(?!\\.)\\b')) | default('80') }}"

###############################################################################
# ENSURING VIRTUAL HOST IS CONFIGURED
###############################################################################

- name: "Rendering server configuration lines"
  ansible.builtin.set_fact:
    rendered_lines: |
      server {
      {% for item in nginx_server | dict2items if item.value is not none %}
        {{ item.key }} {{ item.value }};
      {% endfor %}
      }

- name: "Ensuring Nginx configuration matches template"
  ansible.builtin.copy:
    content: "{{ rendered_lines }}"
    dest: "{{ nginx_etc_directory }}/sites-available/{{ nginx_site.name }}_{{ nginx_server_port }}"
    mode: "0640"
    owner: "root"
    group: "root"
