---
###############################################################################
#
# server_enabled.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# SETTING VARIABLES
###############################################################################

- name: "Setting what variables are configured"
  ansible.builtin.set_fact:
    nginx_server: "{{ nginx_server_record.server_name }}"
    nginx_configuration: "{{ nginx_server_record }}"
  when: nginx_server_record is defined

- name: "Checking if required variables are defined"
  ansible.builtin.assert:
    that:
      - nginx_server is defined
    fail_msg: "All tests did not pass"

###############################################################################
# ENSURING SERVER IS ENABLED
###############################################################################

- name: "Create a symbolic link for server"
  ansible.builtin.file:
    src: "{{ nginx_etc_directory }}/sites-available/{{ nginx_server }}"
    dest: "{{ nginx_etc_directory }}/sites-enabled/{{ nginx_server }}"
    owner: root
    group: root
    state: link

- name: "Writing log"
  ansible.builtin.include_tasks: log_write.yml
  vars:
    iac_log_write: "Ensured {{ nginx_server }} was enabled"
