---
###############################################################################
#
# server_present.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# SETTING VARIABLES
###############################################################################

- name: "Setting variables"
  ansible.builtin.set_fact:
    nginx_ssl_certificate_type: "{{ nginx_site.ssl_certificate_type | default(nginx_default_ssl_certificate_type) }}"

- name: "Checking if required variables are defined"
  ansible.builtin.assert:
    that:
      - nginx_etc_directory is defined
      - nginx_site.name is defined
      - nginx_server is defined
    fail_msg: "All tests did not pass"

###############################################################################
# CHECKING IF THERE IS NEED FOR CERTIFICATE
###############################################################################

- name: "Checking for certificate"
  ansible.builtin.include_tasks: certificate_present.yml
  vars:
    nginx_server_name: "{{ nginx_site.name }}"
    nginx_ssl_certificate_key: "{{ nginx_server.ssl_certificate_key }}"
    nginx_ssl_certificate: "{{ nginx_server.ssl_certificate }}"
  when: nginx_server.ssl_certificate_key is defined and nginx_server.ssl_certificate is defined and nginx_ssl_certificate_type == 'selfsigned'

- name: "Setting variables"
  ansible.builtin.set_fact:
    nginx_server_port: "{{ nginx_server.listen | regex_search('([0-9]{2,5})(?!\\.)\\b') }}"

###############################################################################
# ENSURING VIRTUAL HOST IS CONFIGURED
###############################################################################

- name: "Rendering server configuration lines"
  ansible.builtin.set_fact:
    rendered_lines: |
      server {
      {% for item in nginx_server | dict2items if item.value is not none %}
        {{ item.key }} {{ item.value }};
      {% endfor %}
      }

- name: "Ensuring Nginx configuration matches template"
  ansible.builtin.copy:
    content: "{{ rendered_lines }}"
    dest: "{{ nginx_etc_directory }}/sites-available/{{ nginx_site.name }}_{{ nginx_server_port }}"
    mode: "0640"
    owner: "root"
    group: "root"

- name: "Writing log"
  ansible.builtin.include_tasks: log_write.yml
  vars:
    iac_log_write: "Ensured servers in site {{ nginx_site.name }} were available"
